# Import Dependencies

In [1]:
%pip install stable-baselines3

  Using cached gymnasium-0.29.1-py3-none-any.whl.metadata (10 kB)
Using cached gymnasium-0.29.1-py3-none-any.whl (953 kB)
  Attempting uninstall: gymnasium
    Found existing installation: gymnasium 1.0.0a2
    Uninstalling gymnasium-1.0.0a2:
      Successfully uninstalled gymnasium-1.0.0a2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
shimmy 2.0.0 requires gymnasium>=1.0.0a1, but you have gymnasium 0.29.1 which is incompatible.

[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
%pip install gym
%pip install gym[classic_control]


[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
zsh:1: no matches found: gym[classic_control]
Note: you may need to restart the kernel to use updated packages.


In [3]:
import os
import gym # for openai gym
from stable_baselines3 import PPO # Algorithm
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

# Load Environment

In [4]:
env_name = 'CartPole-v0'

In [5]:
env = gym.make(env_name)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gym/envs/registration.py:555: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(


In [6]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0
    while not done:
        env.render() # Graphical representation of the episode.
        action = env.action_space.sample() # Generate a random action
        next_state, reward, done, info, _ = env.step(action)
        score += reward    
    print(f"Episode: {episode}, Score: {score}")
env.close()

Episode: 1, Score: 11.0
Episode: 2, Score: 16.0
Episode: 3, Score: 40.0
Episode: 4, Score: 20.0
Episode: 5, Score: 18.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gym/envs/classic_control/cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v0", render_mode="rgb_array")
  gym.logger.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


## Understanding The Environment

**Episodes**  
Think of an episode as one full game within the environment.  
Some Environments have a fixed episode length e.g. CartPole which is 200 frames. Others are continuous. e.g. Breakout, play until you run out of lives.

In [7]:
env.reset()

(array([ 0.04945291, -0.00088456,  0.00082668,  0.0273103 ], dtype=float32),
 {})

In [8]:
env.action_space

Discrete(2)

In [9]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [10]:
env.step(1)

(array([ 0.04943522,  0.19422552,  0.00137288, -0.26511168], dtype=float32),
 1.0,
 False,
 False,
 {})

# Train RL Model

In [11]:

%pip install 'shimmy>=0.2.1'

  Using cached gymnasium-1.0.0a2-py3-none-any.whl.metadata (10 kB)
Using cached gymnasium-1.0.0a2-py3-none-any.whl (954 kB)
  Attempting uninstall: gymnasium
    Found existing installation: gymnasium 0.29.1
    Uninstalling gymnasium-0.29.1:
      Successfully uninstalled gymnasium-0.29.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
stable-baselines3 2.3.2 requires gymnasium<0.30,>=0.28.1, but you have gymnasium 1.0.0a2 which is incompatible.

[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [12]:
log_path = os.path.join('training', 'logs')
if not os.path.exists(log_path):
    os.makedirs(log_path)

In [13]:
env = gym.make(env_name)
env = DummyVecEnv([lambda: env]) # Wrapped the environment in a vectorization
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path) 
#  Policy(MLP=Neural network), env, 

Using cpu device


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


**Policies**   
Policy is like the rule which tells the agent how to operate in the environment
SB3 has three policy types: MlpPolicy, CnnPolicy and MultiInputPPolicy.

In [19]:

model.learn(total_timesteps=20000)

Logging to training/logs/PPO_4
-----------------------------
| time/              |      |
|    fps             | 5290 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3466        |
|    iterations           | 2           |
|    time_elapsed         | 1           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.005557725 |
|    clip_fraction        | 0.0488      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.542      |
|    explained_variance   | 0.896       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.209       |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.00667    |
|    value_loss           | 6.2         |
-----------------------------------------
---

# Save & Reload Model

In [20]:
model_path = os.path.join('training', 'saved models')
PPO_Path = os.path.join(model_path,'PPO_Model_Cartpole')
if not os.path.exists(model_path):
    os.makedirs(model_path)

In [21]:
model.save(PPO_Path)

In [22]:
del model

In [23]:
model = PPO.load(PPO_Path, env=env)

# Evaluation

In [24]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:243: UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
  warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")


(200.0, 0.0)

PPO model would be considered solved if the evaluation metric is 200 or higher. Different Algorithms have different evaluation metrics to consider it solved.

**CartPole Reward**   
Reward for CartPole is calculated a s1 point for every step that the pole remains upright(with a max of 200 steps)  
If the pole is more than 15 degrees from the vertical or the cart moves more than 2.4 units from the center the episode ends.

In [25]:
env.close()

# Test Model

In [29]:
# obs = env.reset()
# while True:
#     action, _states = model.predict(obs)
#     obs, rewards, done, info = env.step(action)
#     env.render()
#     if done: 
#         print('info', info)
#         break

info [{'TimeLimit.truncated': True, 'terminal_observation': array([ 0.10402902, -0.01270733,  0.02109799, -0.24954855], dtype=float32)}]


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:243: UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
  warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")


In [36]:
episodes = 5
for episode in range(1, episodes+1):
    obs = env.reset()
    done = False
    score = 0
    while not done:
        env.render() # Graphical representation of the episode.
        action, _ = model.predict(obs) # Generate a random action
        obs, reward, done, info = env.step(action)
        score += reward    
    print(f"Episode: {episode}, Score: {score}")

Episode: 1, Score: [200.]
Episode: 2, Score: [200.]
Episode: 3, Score: [200.]
Episode: 4, Score: [200.]
Episode: 5, Score: [200.]


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:243: UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
  warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")


In [37]:
env.close()

### Steps:

In [38]:
obs = env.reset()

In [42]:
action, _ = model.predict(obs)

In [40]:
model.predict??

Signature:
model.predict(
    observation: Union[numpy.ndarray, Dict[str, numpy.ndarray]],
    state: Optional[Tuple[numpy.ndarray, ...]] = None,
    episode_start: Optional[numpy.ndarray] = None,
    deterministic: bool = False,
) -> Tuple[numpy.ndarray, Optional[Tuple[numpy.ndarray, ...]]]
Source:   
    def predict(
        self,
        observation: Union[np.ndarray, Dict[str, np.ndarray]],
        state: Optional[Tuple[np.ndarray, ...]] = None,
        episode_start: Optional[np.ndarray] = None,
        deterministic: bool = False,
    ) -> Tuple[np.ndarray, Optional[Tuple[np.ndarray, ...]]]:
        """
        Get the policy action from an observation (and optional hidden state).
        Includes sugar-coating to handle different observations (e.g. normalizing images).

        :param observation: the input observation
        :param state: The last hidden states (can be None, used in recurrent policies)
        :param episode_start: The last masks (can be None, used in recurren

In [43]:
env.action_space.sample()

1

In [44]:
env.step(action)

(array([[ 0.0215057 , -0.1806088 , -0.03177781,  0.3085903 ]],
       dtype=float32),
 array([1.], dtype=float32),
 array([False]),
 [{'TimeLimit.truncated': False}])

# Viewing Logs in a Tensorboard

In [47]:
training_log_path = os.path.join(log_path,'PPO_4')

In [48]:
%pip install tensorboard


[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [49]:
!tensorboard --logdir={training_log_path}

I0807 02:53:54.994399 14473818112 plugin.py:429] Monitor runs begin
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.17.0 at http://localhost:6006/ (Press CTRL+C to quit)
W0807 02:54:23.750689 14507470848 application.py:559] path /apple-touch-icon-precomposed.png not found, sending 404
W0807 02:54:23.810138 14507470848 application.py:559] path /apple-touch-icon.png not found, sending 404
^C


# Adding Callbacks

In [50]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold

In [51]:
env = gym.make(env_name)
env = DummyVecEnv([lambda: env])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gym/envs/registration.py:555: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


In [52]:
stop_callback = StopTrainingOnRewardThreshold(reward_threshold=190, verbose=1)
eval_callback = EvalCallback(env, 
                             callback_on_new_best=stop_callback, 
                             eval_freq=10000, 
                             best_model_save_path=model_path, 
                             verbose=1)

In [53]:
model = PPO('MlpPolicy', env, verbose = 1, tensorboard_log=log_path)

Using cpu device


In [54]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to training/logs/PPO_5


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


-----------------------------
| time/              |      |
|    fps             | 4982 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3190        |
|    iterations           | 2           |
|    time_elapsed         | 1           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.009154245 |
|    clip_fraction        | 0.119       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | -0.0081     |
|    learning_rate        | 0.0003      |
|    loss                 | 5.94        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0181     |
|    value_loss           | 45.5        |
-----------------------------------------
----------------------------------

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


In [55]:
best_model_path = os.path.join(model_path, 'best_model')
model = PPO.load(best_model_path, env=env)

In [56]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:243: UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
  warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")


(197.0, 9.0)

In [57]:
env.close()

# Changing Policy

In [58]:
net_arch=[dict(pi=[128, 128, 128, 128], vf=[128, 128, 128, 128])]

In [59]:
model = PPO('MlpPolicy', env, verbose = 1, policy_kwargs={'net_arch': net_arch})

Using cpu device


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/policies.py:486: UserWarning: As shared layers in the mlp_extractor are removed since SB3 v1.8.0, you should now pass directly a dictionary and not a list (net_arch=dict(pi=..., vf=...) instead of net_arch=[dict(pi=..., vf=...)])
  warnings.warn(


In [60]:
model.learn(total_timesteps=20000, callback=eval_callback)

-----------------------------
| time/              |      |
|    fps             | 4338 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2523        |
|    iterations           | 2           |
|    time_elapsed         | 1           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.015269836 |
|    clip_fraction        | 0.239       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    explained_variance   | -0.00634    |
|    learning_rate        | 0.0003      |
|    loss                 | 2.27        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0283     |
|    value_loss           | 20.8        |
-----------------------------------------
----------------------------------

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


------------------------------
| time/              |       |
|    fps             | 1980  |
|    iterations      | 5     |
|    time_elapsed    | 5     |
|    total_timesteps | 10240 |
------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 1943        |
|    iterations           | 6           |
|    time_elapsed         | 6           |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.013661968 |
|    clip_fraction        | 0.107       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.546      |
|    explained_variance   | 0.841       |
|    learning_rate        | 0.0003      |
|    loss                 | 7.81        |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0078     |
|    value_loss           | 20.6        |
-----------------------------------------
---------------------------

# Using Alternate Algorithm

In [61]:
from stable_baselines3 import DQN

In [62]:
model = DQN('MlpPolicy', env, verbose = 1, tensorboard_log=log_path)

Using cpu device


In [63]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to training/logs/DQN_1
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.954    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 14438    |
|    time_elapsed     | 0        |
|    total_timesteps  | 96       |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.922    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 5157     |
|    time_elapsed     | 0        |
|    total_timesteps  | 165      |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.494    |
|    n_updates        | 16       |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.891    |
| time/               |          |
|    episodes         | 12       |
|    fps              | 

In [64]:
dqn_path = os.path.join(model_path, 'DQN_model')

In [65]:
model.save(dqn_path)

In [66]:
model = DQN.load(dqn_path, env=env)

In [67]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:243: UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
  warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")


(9.6, 0.7999999999999999)

In [68]:
env.close()